name: Web Accessibility Evaluation

on:
  page_build:
  # schedule: # Check your schedule here => https://crontab.guru/
  #   - cron: '55 23 * * 0' # e.g. every Sunday at 23:55
  #
  # THAT'S IT; YOU'RE DONE;
  workflow_dispatch:

########################################################################
# THAT'S IT; YOU DON'T HAVE TO DEFINE ANYTHING IN THE FOLLOWING
########################################################################

jobs:
  run-accessibility-evaluation:
    runs-on: ubuntu-latest
    steps:
      - uses: a11ywatch/github-action@v2.1.9
        with:
          WEBSITE_URL: https://george-gca.github.io/
          SITE_WIDE: true
          SUBDOMAINS: true
          TLD: true
          SITEMAP: true
          FAIL_ERRORS_COUNT: 15
          LIST: true
          FIX: false
          UPGRADE: false
          UPLOAD: true
        env:
          DEFAULT_RUNNERS: htmlcs,axe
          PAGEMIND_IGNORE_WARNINGS: false
          AI_DISABLED: false